services:
  bytebase:
    image: bytebase/bytebase:2.22.1
    ports:
      - "8082:8080"
    environment:
      - BYTEBASE_URL=http://localhost:8082
    volumes:
      - ./bytebase-data:/var/opt/bytebase
    depends_on:
      timescaledb:
        condition: service_healthy

volumes:
  bytebase-data:
    driver: local