apiVersion: v1
kind: Service
metadata:
  name: bytebase-entrypoint
  namespace: bytebase
spec:
  type: ClusterIP
  selector:
    app: bytebase
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080